### PR TITLE
Fixing issue 16

### PR DESCRIPTION
**Pull request by hoyc1**
Fixing issue #16.

### CODE REVIEW

**Comment by hoyc1** [comment]
@rgreen1995, this is now complete. This needs to be merged after this [MR](https://github.com/rgreen1995/PTMCMCSampler/pull/10). However, we can start the review on the [plot.py](https://github.com/hoyc1/PTMCMCSampler/blob/issue16/PTMCMCSampler/plot.py) and [result.py](https://github.com/hoyc1/PTMCMCSampler/blob/issue16/PTMCMCSampler/result.py) scripts as these will not change. You can see how it works by looking at the updated [simple.ipynb](https://github.com/hoyc1/PTMCMCSampler/blob/issue16/examples/simple.ipynb) notebook

**Comment by rgreen1995** [comment]
This looks awesome! Let's go through these Monday and merge them then?

**Comment by rgreen1995** [comment]
What's left to do on the other mr ? We could probably move ahead and create a new issue if it's just the prior proposal that needs to be implemented.

**Comment by hoyc1** [comment]
@rgreen1995, this is ready to be merged.

**Pull request merged**
